#!/usr/bin/env ruby

require_relative 'completion'

class CalculationTriggerCompletion < Completion
  def all_matches
    projects = %x( find "#{Dir.pwd}/src" -iname 'CalculationTriggerEvent.java' | xargs grep 'parameters\\[0\\]\\.equals\\|equals\(parameters' | sed 's/.*\\"\\(.*\\)\\".*/\\1/' ).split("\n")
    return projects
  end
end

puts CalculationTriggerCompletion.new(ENV["COMP_LINE"]).matches
#puts CalculationTriggerCompletion.new("123").matches
exit 0
