#!/usr/bin/env ruby

require_relative 'completion'

class ClearCacheCompletion < Completion
  def all_matches
    projects = %x( find "#{Dir.pwd}/src" -iname 'ClearCacheEvent.java' | xargs grep 'parameters\\[0\\]\\.equals\\|equals\(parameters' | sed 's/.*\\"\\(.*\\)\\".*/\\1/' ).split("\n")
    return projects
  end
end

puts ClearCacheCompletion.new(ENV["COMP_LINE"]).matches
exit 0
