#!/usr/bin/env ruby

require_relative 'completion'

class EventGeneratorCompletion < Completion
  def all_matches
    files = Dir.glob("#{Dir.pwd}/src/net/novacom/clienttel/event/*.java").map do |f| 
      File.basename(f, ".java")
    end
    files - %w(Event EventListener EventManager EventServlet BookingListener ParameterEvent Notification)
  end
end

puts EventGeneratorCompletion.new(ENV["COMP_LINE"]).matches
exit 0
