#!/usr/bin/env ruby

require_relative './completion'

class ProjectCompletion < Completion
  def all_matches
    `ls ~/code/`.split
  end
end

puts ProjectCompletion.new(ENV["COMP_LINE"]).matches
exit 0
